version: '3'

services:
  client:
    image: wsinfo/netcore-cache.ui
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:80"
      - "44336:44336"
    links:
      - serverApi
    networks:
      - netCoreCache-network

  serverApi:
    image: wsinfo/netcore-cache.service    
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production    
    networks:
       - netCoreCache-network
    depends_on:
      - "netcore-cache.redis"

  netcore-cache.redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
       - netCoreCache-network


networks: 
  netCoreCache-network:
    driver: bridge