version: '3'

services:
  client:
    image: netcore-cache.ui:dev
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    network:

  serverApi:
    image: netcore-cache.service:dev
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "netcore-cache.redis-DEV"

  netcore-cache.redis-DEV:
    image: redis:alpine
    ports:
      - "16379:6379"
    networks:
       - netCoreCache-network-DEV

  nginx:
    image: netcore-cache.proxy:dev
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "81:80"
      - "8287:8286"
    links:
      - client
      - serverApi
      - netcore-cache.redis-DEV

networks: 
  netCoreCache-network-DEV:
    driver: bridge