version: '3'

services:
  serverApi:
    image: netcore-cache.service:prod
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
       - netCoreCache-network
    depends_on:
      - "netcore-cache.redis"

  netcore-cache.redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
       - netCoreCache-network

  client:
    image: netcore-cache.ui:prod
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:80"
      - "44336:44336"
    links:
      - serverApi
    networks:
      - netCoreCache-network

networks: 
  netCoreCache-network:
    driver: bridge